### ISSUE TITLE
Query builder and Marshmallows

### ISSUE THREAD

**Issue by frafall** [demoskp/flask-query-builder#2]
I looking at using query builder but I'm struggling with combining it with Marshmallows.

First approach was to let Marshmallows not rais exception on unknown parameters, this way I could let Marshmallows parse other parameters as usual.

But, ideally I would like to have the API described in Swagger/OpenAPI, with the above approach the Query Builder arguments are not visible in API description.

Do you have any hints on how to have the Query Builder filter.../sort described in OpenAPI? For consistency a Marshmallows approach would be best but I'm open for input :)

best regards

**Comment by frafall** [comment]
In your documentation you use a mix syntaxes, I only got the first to work, is the second supposed to work as well?
`
1) /user?filter[name]=..
2) /user?filter=[name]=...
`

**Comment by frafall** [comment]
Hmm, according to your regexp filter=[name] is not supposed to work so a documentation update is in place?

 `matches = re.findall(r"(?<=filter\[).[a-z._-]+", arg)`

**Comment by demoskp** [comment]
> I looking at using query builder but I'm struggling with combining it with Marshmallows.
> 
> First approach was to let Marshmallows not rais exception on unknown parameters, this way I could let Marshmallows parse other parameters as usual.
> 
> But, ideally I would like to have the API described in Swagger/OpenAPI, with the above approach the Query Builder arguments are not visible in API description.
> 
> Do you have any hints on how to have the Query Builder filter.../sort described in OpenAPI? For consistency a Marshmallows approach would be best but I'm open for input :)
> 
> best regards

Do you have an example of the way you are using it?

**Comment by demoskp** [comment]
> In your documentation you use a mix syntaxes, I only got the first to work, is the second supposed to work as well?
> 
> ```
> 1) /user?filter[name]=..
> 2) /user?filter=[name]=...
> ```

The first one is the only valid one, I will check and remove any invalid references.

**Comment by demoskp** [comment]
It depends what creates the documentation for swagger, in my projects I use apispec and the way I have it setup it reads from the flask_restful Resource docblock i.e.

      parameters:
        - in: query
          name: filter[name]
        - in: query
          name: filter[year]

**Comment by frafall** [comment]
> > I looking at using query builder but I'm struggling with combining it with Marshmallows.
> > First approach was to let Marshmallows not rais exception on unknown parameters, this way I could let Marshmallows parse other parameters as usual.
> > But, ideally I would like to have the API described in Swagger/OpenAPI, with the above approach the Query Builder arguments are not visible in API description.
> > Do you have any hints on how to have the Query Builder filter.../sort described in OpenAPI? For consistency a Marshmallows approach would be best but I'm open for input :)
> > best regards
> 
> Do you have an example of the way you are using it?

I am using flask-smorest, sample code below, works nicely except for the api description of filtering/sorting.

best regards,
```
blp = Blueprint("TestFilters", "testfilters", description="Test filtering/sorting queries in API")

class FilterListSchema(Schema):
    firm    = fields.Str(required=False)

@blp.route("")
class GetFilter(MethodView):
    """Test filtering methods
    """

    @blp.arguments(FilterListSchema, location='query', as_kwargs=True)
    @blp.response(200, UserSchema(many=True, only=('id', 'fullname')))
    @blp.doc(operationId="getFilter")
    def get(self, *args, **kwargs):
        """Sort and filter query results
        """
        query = UserModel.query.filter(UserModel.id < 500)

        try:
            users = (
                QueryBuilder(model=UserModel, query=query)
                    .allowed_filters([
                        AllowedFilter.partial("name", "fullname"),
                        AllowedFilter.exact('id')
                    ])
                    .allowed_sorts([
                        AllowedSort.field('name', 'fullname'),
                        AllowedSort.field('id')
                    ])
                    .query
                    .all()
            )

        except InvalidFilterException:
            abort(422, message='Invalid filter')

        except InvalidSortException:
            abort(422, message='Invalid sort')

        return users
```

**Comment by frafall** [comment]
My best bet so far is to encode the fields into Marshmallows specifically, this is a crude approach but works. 

The downside is that I have to keep the Marshmallows schema and the QueryBuilder code in sync and the arguments to the sort/filter in the schema is not detailed, just a bag of strings ... but it's a step forward.

```
class FilterListSchema(Schema):
    firm            = fields.Str(required=False)
    sort            = fields.Str(required=False)

    class Meta:
        include = { 
            'filter[id]':   fields.Str(required=False),
            'filter[name]': fields.Str(required=False)
        }
```

best regards

**Comment by frafall** [comment]
The above integration with flask-smorest/Marshmallows works for me, I considered adding custom types to handle "string or list of strings" but found this redundant as it would not provide much more doc in OpenAPI while argument security is handled by query builder anyhow.

Keep up the good work :)
